# Generated by Django 4.2.16 on 2024-11-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file", models.BinaryField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed",
                    models.CharField(
                        choices=[("processed", "Processed"), ("final", "Final")],
                        default="processed",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
