# Generated by Django 4.2.16 on 2024-11-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="processed", new_name="process_status",
        ),
    ]
