# Generated by Django 4.2.16 on 2024-12-02 00:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_rename_processed_order_process_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="file",
            field=models.FileField(upload_to="uploads/", verbose_name="File Path"),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False, verbose_name="Id"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="process_status",
            field=models.CharField(
                choices=[("processed", "Processed"), ("final", "Final")],
                default="processed",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_description",
                    models.CharField(
                        max_length=200, verbose_name="Product Description"
                    ),
                ),
                (
                    "item_number",
                    models.CharField(max_length=200, verbose_name="Item Number"),
                ),
                (
                    "vendor_number",
                    models.CharField(max_length=100, verbose_name="Vendor Name"),
                ),
                ("quantity", models.CharField(max_length=100, verbose_name="quantity")),
                (
                    "unit_price",
                    models.CharField(max_length=100, verbose_name="unit price"),
                ),
                ("total", models.CharField(max_length=200, verbose_name="total")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details",
                        to="order.order",
                        verbose_name="Order Number",
                    ),
                ),
            ],
        ),
    ]
