# Generated by Django 4.2.16 on 2024-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_file_alter_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="best_match",
            field=models.CharField(
                default="N/A", max_length=200, verbose_name="Best Match"
            ),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="item_number",
            field=models.CharField(
                default="N/A", max_length=200, verbose_name="Item Number"
            ),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="product_description",
            field=models.CharField(
                default="N/A", max_length=200, verbose_name="Product Description"
            ),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="quantity",
            field=models.CharField(
                default="N/A", max_length=100, verbose_name="quantity"
            ),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="total",
            field=models.CharField(default="N/A", max_length=200, verbose_name="total"),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="unit_price",
            field=models.CharField(
                default="N/A", max_length=100, verbose_name="unit price"
            ),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="vendor_number",
            field=models.CharField(
                default="N/A", max_length=100, verbose_name="Vendor Name"
            ),
        ),
    ]
