# Generated by Django 4.2.16 on 2024-12-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_orderdetails_best_match_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="uploaded_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
