# Generated by Django 4.2.16 on 2024-11-25 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("material", models.CharField(max_length=50, verbose_name="Material")),
                ("size", models.CharField(max_length=10, verbose_name="Size")),
                ("length", models.CharField(max_length=10, verbose_name="Length")),
                ("coating", models.CharField(max_length=50, verbose_name="Coating")),
                (
                    "thread_type",
                    models.CharField(max_length=50, verbose_name="Thread Type"),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
            ],
        ),
    ]
